### ISSUE TITLE
Plugin stopped working this evening. 

### ISSUE THREAD

**Issue by historymaker118** [GuyXY/YouTube-Design-Preserver#3]
Refreshed youtube and suddenly I'm stuck with the crappy new layout. Tried clearing my cache, manually setting the pref cookie, signing in and out of google and restarting my browser (firefox). None of these worked. Any help would be appreciated. I hate the new youtube layout.

**Comment by p00pa** [comment]
16.06.2020 Plugin stopped working (Opera browser)
17.06.2020 It works again (Opera browser)
I better like the "old" youtube layout, it's quicker and "smaller".

**Comment by p00pa** [comment]
17.06.2020 (evening) **Plugin stopped working** (Opera browser)

**Comment by GuyXY** [comment]
YouTube removed the method this add-on was using to set the old layout. I found a workaround tho. The old layout should work again in the newest version for Firefox. An update for the Opera version is coming soon.

**Comment by p00pa** [comment]
Found a solution:  "User-Agent: Googlebot/2.1". Works fine (Opera browser). m.b. u could implement it in your code

**Comment by GuyXY** [comment]
Well, that **is** the workaround that I was talking about. :)
You can see the changes here, if you'd like: https://github.com/GuyXY/YouTube-Design-Preserver/commit/6f3fef82391fe035f77c0f7c03ca54c564e09a20
The newest version for Firefox already uses this method. The Opera version will be released soon.

**Comment by p00pa** [comment]
Consider BingBot as "Old Layout Method2"

**Comment by Mike-source522** [comment]
Just wanted to let ya know that this no longer works for firefox 54.0 (32-bit). I removed the old version and installed your latest one (2.4.0) which was suppose to fix it, but it didn't. Refreshing the page, clearing cache, spamming the "fix it" button.. nothing worked.

**Comment by MZhuravsky** [comment]
Could You be pleased to update the extension for Opera? :-)

**Comment by p00pa** [comment]
"videos?disable_polymer=1"

**Comment by MZhuravsky** [comment]
what does it mean?

**Comment by Black-Platypus** [comment]
> > "videos?disable_polymer=1"
> 
> what does it mean?

That's an older way of asking YouTube for the old layout (or rather, telling it to disable the new one) 

You used to be able to append "disable_polymer=1" to the Query String (with a preceding "?" if none present yet, otherwise "&")
YouTube are always rolling out changes at different times for different people, but as of a couple of weeks ago, it stopped working for me. Chances for this working for anybody now are increasingly slim.

**Comment by p00pa** [comment]
Iv found a temp. solution:  AFTER starting any yt-video(in "Polymer layout") u should trigger "UserAgent" parameter, i.e. from "Default" to "GoogleBot". It works right now. And here is the URL for "old layout" subscriptions : ....youtube.com/feed/subscriptions?disable_polymer=true&flow=1
